[CI] Fix fetching error in git install
"""
 E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/libd/libdbi-perl/libdbi-perl_1.640-1ubuntu0.1_amd64.deb  404  Not Found [IP: 52.168.50.79 80]
Fetched 54.0 MB in 6s (8360 kB/s)
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
"""